### PR TITLE
Fix lookup for rule names containing _ or $ characters

### LINKED ISSUE #28: "Goto/Peek Definition" doesn't work when rule name contains underscores
For example with this grammar:

```
start = multi_stmt

multi_stmt = (stmt ";")+

stmt = "HELLO"
```

The Peek Definition functionality works fine with the `stmt` rule:

peek-stmt

But when I try to peek at the `multi_stmt` rule, it doesn't work. Further more, when I hover over the `stmt` part of `multi_stmt`, it peeks at the `stmt` rule:

peek-multi_stmt

Similar problem happens when using the `$` character inside rule name. In that case even syntax highlighting doesn't consider `$` to be part of the name:

peek-dollar

### PR DESCRIPTION
**Pull request by nene**
Simple fixes in regexes.

Fixes #28

### CODE REVIEW

**Comment by hildjj** [comment]
How important is it to you that `$` be valid?  I'm worried about interactions with the variables and function names that peggy creates, which all have `$` in them to be in a separate namespace.

**Comment by nene** [comment]
I made use of the `$` characters in a Peggy plugin that I wrote, where  in my grammar I had rules like:

```
statement$mysql
  = select / create_database / create_view 

statement$sqlite
  = select / create_view
```

which I later transformed by the plugin. Initially I was using the underscore character, but then I realized that Peggy allows `$` character as well, which was much more suitable for me, as I sort of wanted to have it look like custom syntax, while at the same time still being valid Peggy grammar.

At the moment I switched away from that approach, so for now I don't directly need it. Though I might decide to switch back to that approach later.

**Comment by hildjj** [comment]
Oh!  Heh.  I completely misunderstood what I was looking at, sorry.  Yes, I'll take this change.

**Comment by hildjj** [comment]
I hit `merge` just a touch too quickly.  Would you please send me another quick PR to add yourself to the AUTHORS file, please?

**Comment by nene** [comment]
sure...

**Pull request merged**
